---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCaf8GNUcQ9C54bTJeLQqGkagwrmbtLjvkQoc+rmdG+RBl3aat83wZDcpdlPDJqZQPpG6O1VuaDQqlmRWd14vGveiU7OfdbThUkXbqCRBVRCXQPL5jiMrtC5ZZkFlHtoQKEhpVnpakI0er5bvyFK4T6JKsytu1e/dDbQtOJnoFHtecbhr+ZNP2XMqoYbVyfBH2chzzHpDtj3KI9cFlkABZ7bk9kd4QrJir5NWRKOOxWFXif+SPcXjQoJu+rIvV3QQPSBrJYyrbfL0PfEVZ8nLGrXUfzgPEzTLKZZgXEw+ofVdiQ+eSmztWf6AitgxXC5uGZKNTvH2Xfo42vtyrKDn/iC1pM0kjXAuhJQhjJiccHazcFEOZAwIi0ESlRyEMh9UVLtXmIX/AnTaLwanvYlk4BlNnnHsTy+6+wBDrsD9o5tktuSQ4AOGACTcX5JRYDf5os8c5nAEfIP3HZFkI5Rpe1VIMkkVwP8ADfxKi0ZmPTR7ZOpGjErQkb7k7oWndwQdGm9GLmQ0/eOzTIeKgg9F0fXyOrX8WsA8kAcxlCdmUmuIzpt7UqjrQvU6SZzqtJ12z1/57zi8h8wuBQWkTMlQr4du1zKQobnLBf9zf79gCA6u11F2pQfesEf05NSflIF2p9OJhbLxo+eHWkpCnDcgsEYgEqcyCakSJ+SfvSPYLzl+GB7yu1FDTYEG5swhshMb2E8fMY0HugWC+AvpO/Yi7J6WnhZezTjBTA0ZDOsQp16w==
    admin-user: AgCIrxQ16ZV0FKy7/w2DBkcWBFf8s+OUR2KqBs6uDD/+JrVv8af3vUDKSTRY0r5A+CVLizUHQ4dInqgHPbINYBM6qneGs5bHGV5YPKrqevF6g3r+Sk6LqSSomv4jqyuHAQ+dPIMsFaJm0Emrv48BxOX0YZQXALz3EO/pQbmz/yMdOCxMc2TzkS0oba/zZQ8qQtU0ZQKZfsYLnNQeWilhG1VrVImB2BbIzyEjxNGk5/dpX5Yu1lS3orp8mTX4kn5gaZSQdLaozxgRYvrMU7qbZrAhwmRVTBq/kbTLtYxIFzOsetBOltlktkpgY/aZElKdSA7vOk9OxgSS8JvG7eZOC77k2DfAH39tiJWiRGWgd49T4tgccQmL3h6tZyh9Dz8GxfqobIIW8J6yiUHaYFg5JXzr/mGrusmavaJD7PRHzUo9os/mscBcR1GBKGjrUzTS6/o8QUYF69Z4VNwynNraQjXMk3B4snt/GVtqmO32Cat1pnXDjZ+h/nEdb65AGTiLeENrH6Nsh0LaUNymTq2VHaqnRAUhk2YO4epelwG917v3PnLJdJYF3ZCsYHF8cSAF9ZP1ttsDGiCwL5h+FSGGZPWfUqMO4lQNQCCXhK/DblK/C2ZRg4IL4ggFogvGukgLbZtKiE8TI/rhbBoGKhy2qgCg2OhQfEPfzJ7mvk3RSiVHn0juo8TPNsjUUdPM9579rw2HT2QpmQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-admin
      namespace: observability
    type: Opaque
