apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatwoot.fullname" . }}-config
  labels:
    {{- include "chatwoot.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  RAILS_ENV: "production"
  INSTALLATION_ENV: "docker"
  RAILS_LOG_TO_STDOUT: "true"
  POSTGRES_HOST: {{ include "chatwoot.postgresHost" . | quote }}
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: {{ .Values.postgres.username | quote }}
  POSTGRES_DATABASE: {{ .Values.postgres.database | quote }}
  REDIS_URL: "redis://{{ include "chatwoot.redisHost" . }}:6379"
  FRONTEND_URL: {{ .Values.frontendUrl | quote }}
  RAILS_MAX_THREADS: {{ .Values.web.railsMaxThreads | quote }}
